/**
 * @file Automatically generated by barrelsby.
 */

export * from './auth.dto';
export * from './delete-review.dto';
export * from './insert-review.dto';
export * from './instructor-id.dto';
export * from './review.dto';
